fix: improve adapter and model for supports any javascript platforms
casbin/node-casbin pull request #267
Opened 2021-05-03 12:54 UTC by nodece

BREAKING CHANGE:
- remove `enforcer.loadModel()`
- `enforcer.initWithFile()` has been deprecated, use `initWithModelAndAdapter()` instead
- `enforcer.initWithString()` has been deprecated, use `initWithModelAndAdapter()` instead
- `enforcer.initWithAdapter()` has been deprecated, use `initWithModelAndAdapter()` instead
- `newModel()` has been deprecated, use `new Model()` instead
- `Config.newConfig()` has been deprecated, use `Config.newConfigFromText()` instead
- remove `readFile` and `writeFile` from `util`
- move `batchFileAdapter`, `defaultFilteredAdapter` and `fileAdapter` to `casbin/lib/esm/adapter`, and rename `DefaultFilteredAdapter` to `FilteredAdapter`
- `newEnforcer()` no longer supports the incoming file path and needs to pass model and adapter instances

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

2021-05-03 12:56 UTC, nodece commented
hi @harveyappleton and @Sefriol, could you review this pr?

2021-05-03 14:04 UTC, Sefriol reviewed
I think the changes are good, but I am just pondering if this is the right way to do it.

2021-05-03 14:26 UTC, hsluoyz commented
@Zxilly

2021-05-03 14:38 UTC, hsluoyz requested changes
I don't think so many breaking changes are necessary. This will bring troubles to our existing Node-Casbin users. It's not worth doing it just for adapting to browser version Casbin.

2021-05-03 15:43 UTC, nodece commented on README.md
> +const { FileAdapter } = require('casbin/lib/cjs/adapter/node');
I think we should keep the `FileAdapter` in this package.

2021-05-04 01:19 UTC, hsluoyz commented
Closed for now.

2021-05-04 01:19 UTC, closed without merging

2021-05-04 14:06 UTC, Sefriol commented
Yeah. Unless you want to release 6.0 version and keep 5.x updated for some time, there isn't really good way to do this.