Fix: *matcher result should be boolean or number* for  KeyGet2
casbin/node-casbin pull request #347
Opened 2022-02-12 13:22 UTC by Shivansh-yadav13

- #332 
- please suggest changes if required.

2022-02-20 15:09 UTC, hsluoyz commented
@nodece @Zxilly plz review

2022-02-20 15:10 UTC, hsluoyz commented
@Shivansh-yadav13 

1. Don't fix two bugs in one PR. Separate into two PRs.
2. AT the issue sender to review

2022-02-20 16:07 UTC, Shivansh-yadav13 commented
@tomfriedhof can you please review and suggest changes if required.

2022-02-20 16:15 UTC, Zxilly requested changes

2022-02-20 16:15 UTC, Zxilly commented on src/coreEnforcer.ts
>              throw new Error('matcher result should be boolean or number');
please also update error hint

2022-02-21 14:15 UTC, grzegorz-kap commented
@Shivansh-yadav13 , when I was debugging it the value of 'result' was undefined.

In our implementation, we have multiple instances of Casbin enforcer.

Steps to reproduce:
1. Create a new Enforce with an empty permission set and call enforce
2. Create a new Enforce with some permissions and call enforce (an error is thrown: `matcher result should be boolean or number` - result is undefined)
3. Repeat step 2 (no error)



model:
```
[request_definition]
r = sub, dom, obj, act, v

[policy_definition]
p = sub, dom, obj, act, exp

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act && eval(p.exp)
```

2022-02-22 13:43 UTC, Shivansh-yadav13 commented
@grzegorz-kap is it possible if you can show the code or any example because I'm not getting the same error by following the steps I might be doing something wrong.

Also, I realized that I don't get the error `matcher result should be boolean or number` when using `keyGet2` alone but when I use it with role_definition

2022-02-23 11:50 UTC, Shivansh-yadav13 commented
This is what happening

```js
const enforcer1 = await newEnforcer('examples/test_model.conf');
await enforcer1.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });

const enforcer2 = await newEnforcer('examples/test_model.conf', 'examples/test_policy.csv');
await enforcer2.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });
```
**Error -->** `matcher result should be boolean or number`

```js
const enforcer1 = await newEnforcer('examples/test_model.conf', 'examples/test_policy.csv');
await enforcer1.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });

const enforcer2 = await newEnforcer('examples/test_model.conf');
await enforcer2.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });
```
**No Error**

```js
const enforcer1 = await newEnforcer('examples/test_model.conf');
await enforcer1.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });

const enforcer2 = await newEnforcer('examples/test_model.conf');
await enforcer2.enforce('sub', 'dom', '/data1', 'read', { office: 'london', floor: 'first' });
```
**No Error**

2022-02-27 04:18 UTC, Shivansh-yadav13 commented
@grzegorz-kap Ig the error you are facing is resolved after #348, can you please confirm.

2022-03-01 14:12 UTC, nodece commented
Could you add unit tests to cover this case?

2022-03-02 03:08 UTC, Zxilly approved these changes
lgtm

2022-03-02 05:13 UTC, merged